apiVersion: apps/v1
kind: Deployment
metadata:
  name: mock-test-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mock-test-app
  template:
    metadata:
      labels:
        app: mock-test-app
    spec:
      containers:
        name: mock-test
        image: mock-test:latest
        ports:
          - containerPort: 8085

#service type load balancer
---
apiVersion: v1
kind: Service
metadata:
  name: mock-test-svc
spec:
  selector:
    app: mock-test-app
  ports:
    - protocol: TCP
      port: 8085
      targetPort: 8085
  type: LoadBalancer